[package]
name = "kvs"
version = "0.1.0"
authors = ["Seon Woo Kim<seonwoo960000.kim@gmail.com>"]
description = "A key-value store"
edition = "2018"

[dependencies]
clap = "2.32.0"

[dev-dependencies]
assert_cmd = "2.0.16"
predicates = "3.1.2"